name: akofood client deploy
on:
  push:
    branches:
      - main

env:
  AWS_S3_BUCKET: akofood-bucket-for-deploy
  AWS_S3_BUCKET_DIR: akofood-client-deploy
  AWS_CODE_DEPLOY_APPLICATION: akofood-application
  AWS_CODE_DEPLOY_GROUP: akofood-client-group

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: yarn install --frozen-lockfile

      - name: Build # React Build
        run: yarn build
        env:
          CI: ""

      - name: zip create
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_AND_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_AND_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_AND_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_AND_S3_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ${{ secrets.AWS_REGION }} ./$GITHUB_SHA.zip s3://$AWS_S3_BUCKET/$AWS_S3_BUCKET_DIR/$GITHUB_SHA.zip

      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }}
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }}
          --s3-location bucket=$AWS_S3_BUCKET,key=$AWS_S3_BUCKET_DIR/$GITHUB_SHA.zip,bundleType=zip
